FROM python:3.7-buster

ENV PORT=8000
ENV LOG_LEVEL="INFO"
ENV ENABLE_UVLOOP="True"
ENV API_BASE_PATH="/"
ENV MAX_NEWSFEEDS="1024"
ENV EVENTS_QUEUE_SIZE="16"
ENV EVENTS_PER_NEWSFEED="1024"
ENV SUBSCRIPTIONS_PER_NEWSFEED="1024"
ENV NEWSFEED_ID_LENGTH="128"
ENV PROCESSOR_CONCURRENCY="4"

ENV EVENT_STORAGE_DSN="NOTSET"

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="${PYTHONPATH}:/code/src/"

WORKDIR /code
COPY . /code/

RUN pip install --upgrade pip \
 && pip install -r requirements.txt

EXPOSE $PORT

CMD ["python", "-m", "newsfeed"]
