version: 1
disable_existing_loggers: True
formatters:
  verbose:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
handlers:
  console:
    level: "DEBUG"
    class: "logging.StreamHandler"
    formatter: "verbose"
root:
  level: "DEBUG"
  handlers: ["console"]
loggers:
  asyncio:
    level: "INFO"
    handlers: ["console"]
    propagate: False
  newsfeed:
    level: "DEBUG"
    handlers: ["console"]
    propagate: False
